import tshirt1 from "./../../img/fff/tshirt1.png";
import tshirt2 from "./../../img/fff/tshirt2.png";
import tshirt3 from "./../../img/fff/tshirt3.png";
import tshirt4 from "./../../img/fff/tshirt4.png";

import hoodie1 from "./../../img/fff/hoodie1.png";
import hoodie2 from "./../../img/fff/hoodie2.png";
import hoodie3 from "./../../img/fff/hoodie3.png";
import hoodie4 from "./../../img/fff/hoodie4.png";

import shopper1 from "./../../img/fff/shopper1.png";
import shopper2 from "./../../img/fff/shopper2.png";
import shopper3 from "./../../img/fff/shopper3.png";
import shopper4 from "./../../img/fff/shopper4.png";

import other1 from "./../../img/fff/other1.png";
import other2 from "./../../img/fff/other2.png";
import other3 from "./../../img/fff/other3.png";
import other4 from "./../../img/fff/other4.png";


const allItems = [
    {   tshirt: 'tshirt',
        img1: tshirt1,
        img2: tshirt1,
        img3: tshirt1,
        img4: tshirt1,
        img5: tshirt1,
        img6: tshirt1,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   tshirt: 'tshirt',
        img1: tshirt2,
        img2: tshirt2,
        img3: tshirt2,
        img4: tshirt2,
        img5: tshirt2,
        img6: tshirt2,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
        topitem: 'yes',
    },
    {   tshirt: 'tshirt',
        img1: tshirt3,
        img2: tshirt3,
        img3: tshirt3,
        img4: tshirt3,
        img5: tshirt3,
        img6: tshirt3,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   tshirt: 'tshirt',
        img1: tshirt4,
        img2: tshirt4,
        img3: tshirt4,
        img4: tshirt4,
        img5: tshirt4,
        img6: tshirt4,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   hoodie: 'hoodie',
        img1: hoodie1,
        img2: hoodie1,
        img3: hoodie1,
        img4: hoodie1,
        img5: hoodie1,
        img6: hoodie1,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   hoodie: 'hoodie',
        img1: hoodie2,
        img2: hoodie2,
        img3: hoodie2,
        img4: hoodie2,
        img5: hoodie2,
        img6: hoodie2,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
        topitem: 'yes',
    },
    {   hoodie: 'hoodie',
        img1: hoodie3,
        img2: hoodie3,
        img3: hoodie3,
        img4: hoodie3,
        img5: hoodie3,
        img6: hoodie3,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   hoodie: 'hoodie',
        img1: hoodie4,
        img2: hoodie4,
        img3: hoodie4,
        img4: hoodie4,
        img5: hoodie4,
        img6: hoodie4,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },

    {   shopper: 'shopper',
        img1: shopper1,
        img2: shopper1,
        img3: shopper1,
        img4: shopper1,
        img5: shopper1,
        img6: shopper1,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   shopper: 'shopper',
        img1: shopper2,
        img2: shopper2,
        img3: shopper2,
        img4: shopper2,
        img5: shopper2,
        img6: shopper2,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
        topitem: 'yes',
    },
    {   shopper: 'shopper',
        img1: shopper3,
        img2: shopper3,
        img3: shopper3,
        img4: shopper3,
        img5: shopper3,
        img6: shopper3,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   shopper: 'shopper',
        img1: shopper4,
        img2: shopper4,
        img3: shopper4,
        img4: shopper4,
        img5: shopper4,
        img6: shopper4,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },

    {   other: 'other',
        img1: other1,
        img2: other1,
        img3: other1,
        img4: other1,
        img5: other1,
        img6: other1,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   other: 'other',
        img1: other2,
        img2: other2,
        img3: other2,
        img4: other2,
        img5: other2,
        img6: other2,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
        topitem: 'yes',
    },
    {   other: 'other',
        img1: other3,
        img2: other3,
        img3: other3,
        img4: other3,
        img5: other3,
        img6: other3,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
    },
    {   other: 'other',
        img1: other4,
        img2: other4,
        img3: other4,
        img4: other4,
        img5: other4,
        img6: other4,
        size:[
            's',
            'm',
            'l',
            'xl',
            'xxl',
        ],
        color:[
            'black',
            'white',
        ],
        title: '«SYMBIOSIS»',
        des: 'Oversize T-shirt is a fashionable and comfortable clothing option that is suitable for any time of year. Oversize T-shirts have a loose fit and are often made in several times the size of standard T-shirts. This style provides comfort and freedom of movement, allowing the T-shirt to be worn as casual wear or for sports purposes.',
        fabric: '100% cotton',
        density: '150г/м2',
        type: 'T-shirt',
        price: '599',
        stock: 'In stock',
        topitem: 'yes',
    },

]

export{allItems}